name: CI/CD Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt

      - name: Archive application
        run: |
          # Create a zip that EB can use (exclude git and workflow)
          ZIPFILE=app-${{ github.run_id }}.zip
          zip -r $ZIPFILE . -x ".git/*" ".github/*" "venv/*" "__pycache__/*"
          echo "ZIPFILE=$ZIPFILE" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload zip to S3
        run: |
          aws s3 cp $ZIPFILE s3://${{ secrets.S3_BUCKET }}/$ZIPFILE
          echo "S3_KEY=$ZIPFILE" >> $GITHUB_ENV

      - name: Create EB application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "${{ secrets.EB_APP_NAME }}" \
            --version-label "${{ github.run_id }}" \
            --source-bundle S3Bucket="${{ secrets.S3_BUCKET }}",S3Key="$ZIPFILE"

      - name: Update EB environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "${{ secrets.EB_ENV_NAME }}" \
            --version-label "${{ github.run_id }}"
